server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #nacos注册中心地址
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认端口号 如果别占用会自动+1扫描，直到找到未被占用端口号
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'
