server:
  port: 9530
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #        uri: http://localhost:8001
          #动态配置路由eureka上的服务名称地址，由网关进行负载均衡
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
        - id: payment_route2
          #        uri: http://localhost:8001
          #动态配置路由eureka上的服务名称地址，由网关进行负载均衡
          uri: lb://cloud-payment-service
          predicates:
            Path=/payment/getLB/** #断言,路径相匹配的进行路由



eureka:
  instance:
    hostname: cloud-gateway-service # 服务别名
    prefer-ip-address: true # 访问路径显示ip地址,光标放在服务别名上在显示，左下角ip地址
  client:
    #f表示是否向注册中心注册自己，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #集群方式：注册进7001 和 7002
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #defaultZone: http://localhost:7001/eureka #单机写法
